const OWNER="JohannaGansch",REPO="Meine-Spiele",ROOT="Unity_Spiele/Website",API="https://api.github.com/repos/"+OWNER+"/"+REPO+"/contents/";
const app=document.querySelector("#app"),search=document.querySelector("#search");let entries=[];
async function api(path){let r=await fetch(API+path+"?ref=main");if(!r.ok)throw Error("GitHub API "+r.status);return r.json()}
function base(n){return n.includes(".")?n.slice(0,n.lastIndexOf(".")):n}
function find(a,n,ext){return a.find(x=>base(x.name).toLowerCase()==n.toLowerCase()&&(!ext||x.name.toLowerCase().endsWith(ext)))}
function game(a){return !!find(a,"App",".exe")||a.some(x=>/^B\d+$/i.test(base(x.name)))||a.some(x=>/^V\d+$/i.test(base(x.name)))}
async function txt(f){return f?fetch(f.download_url).then(r=>r.text()).catch(()=>"?"):""}
function esc(s){return String(s||"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
async function show(path=ROOT,name="J.G. Spiele"){app.innerHTML='<div class="wrap">⏳ Lade ...</div>';try{let a=await api(path);if(game(a)){return showGame(path,name,a)}let dirs=a.filter(x=>x.type=="dir");entries=await Promise.all(dirs.map(async d=>{let f=await api(path+"/"+encodeURIComponent(d.name));return{path:path+"/"+encodeURIComponent(d.name),name:d.name,files:f,image:find(f,"Bild")?.download_url||"",desc:await txt(find(f,"Beschreibung")),isGame:game(f)}}));render(name)}catch(e){app.innerHTML='<div class="wrap">❌ '+e.message+'</div>'}}
function render(name){app.innerHTML='<div class="wrap"><div class="crumb" onclick="back()">← Zurück</div><h1 class="title">'+esc(name)+'</h1><div class="cards">'+entries.map((x,i)=>`<article class="card" onclick="openEntry(${i})">${x.image?`<img src="${x.image}">`:`<div class="ph">${x.isGame?'🎮':'📁'}</div>`}<div class="body"><h2>${esc(x.name)}</h2><p>${esc(x.desc||(x.isGame?'Spiel öffnen':'Unterkategorie öffnen'))}</p></div></article>`).join("")+'</div></div>'}
function openEntry(i){let x=entries[i];show(x.path,x.name)}
async function showGame(path,name,a){let appf=find(a,"App",".exe"),b0=find(a,"B0"),bild=find(a,"Bild"),desc=await txt(find(a,"Beschreibung"));let bs=a.filter(x=>/^B\d+$/i.test(base(x.name))).sort((x,y)=>+base(x.name).slice(1)-+base(y.name).slice(1));let vs=a.filter(x=>/^V\d+$/i.test(base(x.name))).sort((x,y)=>+base(x.name).slice(1)-+base(y.name).slice(1));app.innerHTML=`<div class="wrap"><div class="game"><div class="hero" style="background-image:url('${b0?.download_url||bild?.download_url||""}')"><div class="heroText"><button class="back" onclick="back()">← Zurück</button><h1>${esc(name)}</h1><p>${esc(desc||"Keine Beschreibung vorhanden.")}</p></div></div><div class="inside">${appf?`<a class="download" href="${appf.download_url}" download>⬇️ App herunterladen</a>`:""}${b0?`<h2>Bilder</h2><img class="mainpic" src="${b0.download_url}">`:""}${bs.length?`<div class="gallery">${bs.map(x=>`<img src="${x.download_url}">`).join("")}</div>`:""}${vs.length?`<h2>🎬 Videos</h2><div class="videos">${vs.map(x=>`<video controls preload="metadata" src="${x.download_url}"></video>`).join("")}</div>`:""}</div></div></div>`}
function back(){show(ROOT,"J.G. Spiele")}search.oninput=()=>{let q=search.value.toLowerCase();if(q){entries=entries.filter(x=>(x.name+" "+x.desc).toLowerCase().includes(q));render("Suche")}};show();